services:
  studentservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:8080" # Expone StudentService en el puerto 5001 local
  
  courseservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5003:8080" # Expone CourseService en el puerto 5003 local
  
  enrollmentservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5004:8080" # Expone EnrollmentService en el puerto 5004 local
  
  paymentservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5005:8080" # Expone PaymentService en el puerto 5005 local
