apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: academic-system
data:
  ConnectionStrings__StudentConnection: "Host=postgres-service;Database=StudentDb;Username=postgres;Password=postgres123"
  ConnectionStrings__CourseConnection: "Host=postgres-service;Database=CourseDb;Username=postgres;Password=postgres123"
  ConnectionStrings__EnrollmentConnection: "Host=postgres-service;Database=EnrollmentDb;Username=postgres;Password=postgres123"
  ConnectionStrings__PaymentConnection: "Host=postgres-service;Database=PaymentDb;Username=postgres;Password=postgres123"
  RabbitMQ__HostName: "rabbitmq-service"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: academic-system
type: Opaque
data:
  POSTGRES_PASSWORD: cG9zdGdyZXMxMjM= # postgres123 en base64
